apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
    spec:
      initContainers:
        - name: django-init
          image: tsadimas/django:ht
          envFrom:
          - configMapRef:
              name: django-config
          command: ["/bin/bash", "-c", "python manage.py makemigrations && python manage.py migrate"]
      containers:
        - name: django
          image: tsadimas/django:ht
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
          livenessProbe:
            httpGet:
              path: /ht/
              port: 8000
          imagePullPolicy: Always